/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author javie
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        Connect();
        mostrarAllClientes();
        
    }
    
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    public void Disconnect(){
        try {
            rs.close();
            pst.close();
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    public void Connect(){
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            try  {
                con=DriverManager.getConnection("jdbc:mysql://localhost/pruebaparcial", "root", "root");
            } catch (SQLException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }
    
    public void mostrarAllClientes(){
        
        int q;
        try {
            pst=con.prepareStatement("SELECT * FROM cliente");
            rs=pst.executeQuery();
            ResultSetMetaData rss=rs.getMetaData();
            q=rss.getColumnCount();
            
            DefaultTableModel df= (DefaultTableModel)jTable1.getModel();
            df.setRowCount(0);
            SimpleDateFormat f=new SimpleDateFormat("dd-MM-yyyy");
            while(rs.next()){
                Vector v2=new Vector();
                for(int i =1; i<=q;i++){
                    v2.add(rs.getInt("idcliente"));
                    v2.add(rs.getString("Nombre"));
                    v2.add(rs.getString("Apellidos"));
                    v2.add(rs.getString("Estatus"));
                    v2.add(rs.getInt("PrecioMatricula"));
                    v2.add(rs.getInt("Telefono"));
                    v2.add(rs.getString("DNI"));
                    v2.add(rs.getString("Direccion"));
                    Timestamp timestamp = rs.getTimestamp("fechaInicio");   
                    java.util.Date fechaInicio = new java.util.Date(timestamp.getTime());
                    v2.add(f.format(fechaInicio));
                    Timestamp timestamp1 = rs.getTimestamp("fechaFin");   
                    java.util.Date fechaFin = new java.util.Date(timestamp1.getTime());
                    v2.add(f.format(fechaFin));
                   
                }
                df.addRow(v2);
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 36)); // NOI18N
        jLabel1.setText("Lista de clientes");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "IdCliente", "Nombre", "Apellidos", "Estatus", "PrecioMatricula", "Telefono", "DNI", "Direccion" }));

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "IdCliente", "Nombre", "Apellidos", "Estatus", "PrecioMatricula", "Telefono", "DNI", "Direccion", "fechaInicio", "fechaFin"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton2.setText("Nuevo cliente");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Editar cliente");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Eliminar cliente");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Exportar a Excel");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Filtrar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel2.setText("Fecha de:");

        jLabel3.setText("Fecha hasta:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(105, 105, 105)
                        .addComponent(jButton3)
                        .addGap(118, 118, 118)
                        .addComponent(jButton4)
                        .addGap(70, 70, 70)
                        .addComponent(jButton5)
                        .addContainerGap(115, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jButton1)
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton6))
                            .addComponent(jLabel3))
                        .addGap(33, 33, 33))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(314, 314, 314))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)
                        .addComponent(jButton6))
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //añadir nuevo cliente
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        DatosCliente datos=new DatosCliente();
        datos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        String filename = "E:\\Excel exportado.csv";
        try {
            FileWriter fw=new FileWriter(filename);
            pst=con.prepareStatement("SELECT * FROM cliente");
            rs=pst.executeQuery();
            fw.append("NOMBRE, APELLIDOS, ESTATUS, TELEFONO, FECHAFIN");
            fw.append("\n");
            SimpleDateFormat f=new SimpleDateFormat("dd-MM-yyyy");
            while(rs.next()){
                
                fw.append(rs.getString(2));
                fw.append(", ");
                fw.append(rs.getString(3));
                fw.append(", ");
                fw.append(rs.getString(4));
                fw.append(", ");
                fw.append(String.valueOf( rs.getInt(6)));
                fw.append(", ");
                fw.append(String.valueOf(f.format(rs.getDate(10))));
                fw.append("\n");
            }
            JOptionPane.showMessageDialog(this,"Archivo Excel generado con éxito");
            fw.flush();
            fw.close();
            
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            // TODO add your handling code here:
            DefaultTableModel df= (DefaultTableModel)jTable1.getModel();
            int fila=jTable1.getSelectedRow();
            int id=(int) jTable1.getValueAt(fila, 0);
            pst=con.prepareStatement("DELETE FROM cliente WHERE idcliente =?");
            pst.setInt(1,id);
            int k=pst.executeUpdate();
            df.removeRow(fila);
            if(k==1){
                JOptionPane.showMessageDialog(this, "Cliente eliminado con éxito!");
                mostrarAllClientes();
                
            }else{
                JOptionPane.showMessageDialog(this, "Fallo al eliminar el cliente!");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed
    //buscar
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int q;
        try{
        String info=jComboBox1.getSelectedItem().toString();
        if(info.equals("IdCliente")){
            int id=Integer.parseInt(jTextField1.getText());
        pst=con.prepareStatement("SELECT * FROM cliente WHERE idcliente =?");
        pst.setInt(1,id);
        }else if(info.equals("Nombre")){
            String n= jTextField1.getText();
            pst=con.prepareStatement("SELECT * FROM cliente WHERE Nombre LIKE ?");
            pst.setString(1,n);
        }else if(info.equals("Apellidos")){
            String n= jTextField1.getText();
            pst=con.prepareStatement("SELECT * FROM cliente WHERE Apellidos LIKE ?");
            pst.setString(1,n);
        }else if(info.equals("Estatus")){
            String n= jTextField1.getText();
            pst=con.prepareStatement("SELECT * FROM cliente WHERE Estatus LIKE ?");
            pst.setString(1,n);
        }else if(info.equals("PrecioMatricula")){
             int id=Integer.parseInt(jTextField1.getText());
        pst=con.prepareStatement("SELECT * FROM cliente WHERE PrecioMatricula =?");
        pst.setInt(1,id);
        }else if(info.equals("Telefono")){
             int id=Integer.parseInt(jTextField1.getText());
        pst=con.prepareStatement("SELECT * FROM cliente WHERE Telefono =?");
        pst.setInt(1,id);
        }else if(info.equals("DNI")){
            String n= jTextField1.getText();
            pst=con.prepareStatement("SELECT * FROM cliente WHERE DNI LIKE ?");
            pst.setString(1,n);
        }else if(info.equals("Direccion")){
            String n= jTextField1.getText();
            pst=con.prepareStatement("SELECT * FROM cliente WHERE Direccion LIKE ?");
            pst.setString(1,n);
        }else{
            pst=con.prepareStatement("SELECT * FROM cliente");
        }
        
        rs=pst.executeQuery();
        ResultSetMetaData rss=rs.getMetaData();
            q=rss.getColumnCount();
            
            DefaultTableModel df= (DefaultTableModel)jTable1.getModel();
            df.setRowCount(0);
            SimpleDateFormat f=new SimpleDateFormat("dd-MM-yyyy");
            while(rs.next()){
                Vector v2=new Vector();
                for(int i =1; i<=q;i++){
                    v2.add(rs.getInt("idcliente"));
                    v2.add(rs.getString("Nombre"));
                    v2.add(rs.getString("Apellidos"));
                    v2.add(rs.getString("Estatus"));
                    v2.add(rs.getInt("PrecioMatricula"));
                    v2.add(rs.getInt("Telefono"));
                    v2.add(rs.getString("DNI"));
                    v2.add(rs.getString("Direccion"));
                    Timestamp timestamp = rs.getTimestamp("fechaInicio");   
                    java.util.Date fechaInicio = new java.util.Date(timestamp.getTime());
                    v2.add(f.format(fechaInicio));
                    Timestamp timestamp1 = rs.getTimestamp("fechaFin");   
                    java.util.Date fechaFin = new java.util.Date(timestamp1.getTime());
                    v2.add(f.format(fechaFin));
                    
                }
                df.addRow(v2);
            }
        
        
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            // TODO add your handling code here:
            EditarCliente datos=new EditarCliente();
            DefaultTableModel df= (DefaultTableModel)jTable1.getModel();
            int fila=jTable1.getSelectedRow();
            int id=(int) jTable1.getValueAt(fila, 0);
            pst=con.prepareStatement("SELECT * FROM cliente WHERE idcliente =?");
            pst.setInt(1,id);
            rs=pst.executeQuery();
            
            datos.jTextField1.setText(jTable1.getValueAt(fila, 1).toString());
            datos.jTextField2.setText(jTable1.getValueAt(fila, 2).toString());
            datos.jTextField3.setText(jTable1.getValueAt(fila, 3).toString());
            datos.jTextField4.setText(jTable1.getValueAt(fila, 4).toString());
            datos.jTextField5.setText(jTable1.getValueAt(fila, 5).toString());
            datos.jTextField6.setText(jTable1.getValueAt(fila, 6).toString());
            datos.jTextField7.setText(jTable1.getValueAt(fila, 7).toString());
            datos.idcliente=Integer.parseInt(jTable1.getValueAt(fila, 0).toString());
            if(rs.next()){
            Timestamp timestamp = rs.getTimestamp("fechaInicio");
            java.util.Date fechaInicio = new java.util.Date(timestamp.getTime());
            Timestamp timestamp1 = rs.getTimestamp("fechaFin");
            java.util.Date fechaFin = new java.util.Date(timestamp1.getTime());
            datos.jDateChooser1.setDate(fechaInicio);
            datos.jDateChooser2.setDate(fechaFin);
            }
            datos.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    //filtrar
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        try{
        java.util.Date fI=jDateChooser1.getDate();
 
        java.util.Date fF=jDateChooser2.getDate();
     
        int q;
        if(fI!=null && fF !=null){
            java.sql.Date fechaDe=new java.sql.Date(fI.getTime());
            java.sql.Date fechaHasta=new java.sql.Date(fF.getTime());
            SimpleDateFormat f1=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            f1.format(fechaDe);
            f1.format(fechaHasta);
        
            pst=con.prepareStatement("SELECT * FROM cliente WHERE  fechaFin >= ? AND fechaFin <= ?");
            pst.setDate(1, fechaDe);
            pst.setDate(2, fechaHasta);
            rs=pst.executeQuery();
            ResultSetMetaData rss=rs.getMetaData();
            q=rss.getColumnCount();
            
            DefaultTableModel df= (DefaultTableModel)jTable1.getModel();
            df.setRowCount(0);
            SimpleDateFormat f=new SimpleDateFormat("dd-MM-yyyy");
            while(rs.next()){
                Vector v2=new Vector();
                for(int i =1; i<=q;i++){
                    v2.add(rs.getInt("idcliente"));
                    v2.add(rs.getString("Nombre"));
                    v2.add(rs.getString("Apellidos"));
                    v2.add(rs.getString("Estatus"));
                    v2.add(rs.getInt("PrecioMatricula"));
                    v2.add(rs.getInt("Telefono"));
                    v2.add(rs.getString("DNI"));
                    v2.add(rs.getString("Direccion"));
                    Timestamp timestamp = rs.getTimestamp("fechaInicio");   
                    java.util.Date fechaInicio = new java.util.Date(timestamp.getTime());
                    v2.add(f.format(fechaInicio));
                    Timestamp timestamp1 = rs.getTimestamp("fechaFin");   
                    java.util.Date fechaFin = new java.util.Date(timestamp1.getTime());
                    v2.add(f.format(fechaFin));
                   
                }
                df.addRow(v2);
            }
        }else{
            mostrarAllClientes();
        }
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
